In [1]:
import tensorflow as tf
a = tf.constant([[3.0, 1.0], [2.0, 1.0]], dtype=tf.float32)
print (a.shape)
a.set_shape([2, 2])
print (a.shape)
print (a.get_shape())
#print (a.reshape(4, 1))
#a = tf.reshape(a, shape=[4, 1])
#print (a.get_shape())

(2, 2)
(2, 2)
(2, 2)


#### 计算维度

In [21]:
print ("Get shape: ", a.get_shape())
print ("Get return type: ", type(a.get_shape()))
print ("Get return type: ", type(a.shape))

Get shape:  (4, 1)
Get return type:  <class 'tensorflow.python.framework.tensor_shape.TensorShape'>
Get return type:  <class 'tensorflow.python.framework.tensor_shape.TensorShape'>


#### Reshape

In [19]:
a = tf.reshape(a, shape=[4, 1])
print ("After reshape: ", a.get_shape())

After reshape:  (4, 1)


#### 计算元素个数

In [23]:
print (tf.size(a))

Tensor("Size_1:0", shape=(), dtype=int32)


#### 计算秩

In [24]:
print (tf.rank(a))

Tensor("Rank:0", shape=(), dtype=int32)


#### expand_dim
作用同reshape，但可以对placeholder用

In [38]:
b = tf.constant([1.0, 2.0, 3.0, 4.0], dtype=tf.float32)
b1 = tf.expand_dims(b, 0)
print (b1.shape)
b2 = tf.expand_dims(b, 1)
print (b2.shape)
b3 = tf.expand_dims(b, -1)
print (b3.shape)
print ("---------")
c = tf.constant([[1.0, 2.0, 3.0, 4.0], [1.0, 2.0, 3.0, 4.0]])
print (c.shape)
c1 = tf.expand_dims(c, 0)
print (c1.shape)
c2 = tf.expand_dims(c, 1)
print (c2.shape)
c3 = tf.expand_dims(c, 2)
print (c3.shape)
print ("---------")

with tf.Session() as sess:
    print ("Ori c: ", sess.run(c))
    print ("C1: ", sess.run(c1))
    print ("C2: ", sess.run(c2))
    print ("C3: ", sess.run(c3))
    sess.close()

(1, 4)
(4, 1)
(4, 1)
---------
(2, 4)
(1, 2, 4)
(2, 1, 4)
(2, 4, 1)
---------
Ori c:  [[ 1.  2.  3.  4.]
 [ 1.  2.  3.  4.]]
C1:  [[[ 1.  2.  3.  4.]
  [ 1.  2.  3.  4.]]]
C2:  [[[ 1.  2.  3.  4.]]

 [[ 1.  2.  3.  4.]]]
C3:  [[[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]]

 [[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]]]


#### slice tensors

In [46]:
d = tf.constant([[[1,1,1], [2,2,2]], [[3,3,3], [4,4,4]], [[5,5,5], [6,6,6]]], dtype=tf.int32)
print (d.shape)
d1 = tf.slice(d, [1,0,0], [1,1,1])
d2 = tf.slice(d, [1,0,0], [1,1,3])
with tf.Session() as sess:
    print (sess.run(d1))
    print (sess.run(d)[1][0][0])
    print (sess.run(d2))
    

(3, 2, 3)
[[[3]]]
3
[[[3 3 3]]]


#### split tensors

In [66]:
d = tf.constant([[[1, 1], [2, 2], [3, 3], [4, 4]], [[1, 1], [2, 2], [3, 3], [4, 4]]])
print (d.shape)
print (tf.rank(d))
D = tf.split(d, num_or_size_splits=2, axis=1)
#d0, d1 = tf.split(2, 2, d)
print (D[0].shape)

(2, 4, 2)
Tensor("Rank_13:0", shape=(), dtype=int32)
(2, 2, 2)


In [63]:
A = tf.constant([[1, 2, 3], [4, 5, 6]])
print (A.shape)
a0 = tf.split(A, num_or_size_splits=3, axis=1)
a1 = tf.unstack(A, num=3,axis=1)
a2 = tf.split(A, num_or_size_splits=2, axis=0)
a3 = tf.unstack(A, num=2,axis=0)
with tf.Session() as sess:
    print(sess.run(a0))
    print(sess.run(a1))
    print(sess.run(a2))
    print(sess.run(a3))


(2, 3)
[array([[1],
       [4]], dtype=int32), array([[2],
       [5]], dtype=int32), array([[3],
       [6]], dtype=int32)]
[array([1, 4], dtype=int32), array([2, 5], dtype=int32), array([3, 6], dtype=int32)]
[array([[1, 2, 3]], dtype=int32), array([[4, 5, 6]], dtype=int32)]
[array([1, 2, 3], dtype=int32), array([4, 5, 6], dtype=int32)]


#### Concat tensors

In [72]:
d = tf.constant([[[1, 1], [2, 2], [3, 3], [4, 4]], [[1, 1], [2, 2], [3, 3], [4, 4]]])
print (d.shape)
print (tf.rank(d))
D = tf.split(d, num_or_size_splits=2, axis=1)
#d0, d1 = tf.split(2, 2, d)
print (D[0].shape)

E = tf.concat([D[0], D[1]], axis=-1)
print (E.shape)

(2, 4, 2)
Tensor("Rank_18:0", shape=(), dtype=int32)
(2, 2, 2)
(2, 2, 4)


In [77]:
d2 = tf.constant([[1, 1], [2, 2], [3, 3]])
print (d2.shape)
D2 = tf.split(d2, num_or_size_splits=3)
print (D2[0].shape)
E2 = tf.concat(D2, axis=-1)
print (E2.shape)
with tf.Session() as sess:
    print ("d2: ", sess.run(d2))
    print ("E2: ", sess.run(E2))
    sess.close()

(3, 2)
(1, 2)
(1, 6)
d2:  [[1 1]
 [2 2]
 [3 3]]
E2:  [[1 1 2 2 3 3]]


#### Transpose

In [7]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
print (x.shape)
x_t = tf.transpose(x)
print (x_t.shape)

x1 = tf.expand_dims(x, -1)
print ("x1 shape: ", x1.shape)
x1_t = tf.transpose(x1, perm=[2, 1, 0])
print ("x1_t shape: ", x1_t.shape)
with tf.Session() as sess:
    print ("x: ", sess.run(x))
    print ("x_t: ", sess.run(x_t))
    print ("x1: ", sess.run(x1))
    print ("x1_t: ", sess.run(x1_t))
    sess.close()

(2, 3)
(3, 2)
x1 shape:  (2, 3, 1)
x1_t shape:  (1, 3, 2)
x:  [[1 2 3]
 [4 5 6]]
x_t:  [[1 4]
 [2 5]
 [3 6]]
x1:  [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
x1_t:  [[[1 4]
  [2 5]
  [3 6]]]


#### Reduce sum and Redum mean

In [11]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
x_sum = tf.reduce_sum(x, axis=-1)
x_mean = tf.reduce_mean(x, axis=-1)
print (x.shape)
print (x_sum.shape)
with tf.Session() as sess:
    print ("x: ", sess.run(x))
    print ("x_sum: ", sess.run(x_sum))
    print ("x_mean: ", sess.run(x_mean))
    sess.close()

(2, 3)
(2,)
x:  [[1 2 3]
 [4 5 6]]
x_sum:  [ 6 15]
x_mean:  [2 5]
